name: Auto Fix Changelog

on:
  pull_request:
    paths:
      - autoware_lanelet2_map_validator/CHANGELOG.rst

jobs:
  fix-changelog:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply Fixes to CHANGELOG.rst
        run: |
          START_WORD=https://github.com/tier4/autoware_lanelet2_map_validator/issues/6

          awk -v start_word="$START_WORD" '
          BEGIN { found=0 }
          {
            if (found) {
              gsub("tier4/autoware_lanelet2_map_validator", "autowarefoundation/autoware_tools")
            }
            if ($0 ~ start_word) { found=1 }
            print $0
          }'  autoware_lanelet2_map_validator/CHANGELOG.rst > tmpfile.rst && mv tmpfile.rst autoware_lanelet2_map_validator/CHANGELOG.rst

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add autoware_lanelet2_map_validator/CHANGELOG.rst
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-fix CHANGELOG.rst formatting"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          fi
